declare interface RouteInfo {
  path: string;
  title: string;
  icon: string;
  groupTitle: boolean;
  class: string;
  child?: string[];
  role?: string[];
  submenu: RouteInfo[];
}
export const ROUTES: RouteInfo[] = [

 

  // SUPER ADMIN Modules _________________________________________________________________________
  {
    path: "",
    title: "Analytics",
    icon: "fa  fa-bar-chart",
    class: "",
    groupTitle: false,
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/analytics/order-sales-chart",
        title: "Order & Sale Analytics",
        icon: "pie_chart",
        class: "",
        groupTitle: false,
        role: [""],
        submenu: [],
      },
      {
        path: "/analytics/customer-chart",
        title: "Customer Analytics",
        icon: "pie_chart",
        class: "",
        groupTitle: false,
        role: [""],
        submenu: [],
      },
      {
        path: "/analytics/crm-chart",
        title: "CRM Analytics",
        icon: "pie_chart",
        class: "",
        groupTitle: false,
        role: [""],
        submenu: [],
      },
      {
        path: "/analytics/production-chart",
        title: "Production Analytics",
        icon: "pie_chart",
        class: "",
        groupTitle: false,
        role: [""],
        submenu: [],
      },
      {
        path: "/analytics/chart",
        title: "Location Analytics",
        icon: "pie_chart",
        class: "",
        groupTitle: false,
        role: [""],
        submenu: [],
      },
      {
        path: "/analytics/expense-chart",
        title: "Expense Analytics",
        icon: "pie_chart",
        class: "",
        groupTitle: false,
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "HRA",
    icon: "fa fa-address-card-o",
    class: "",
    groupTitle: false,
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "",
        title: "Employee",
        icon: "",
        class: "",
        groupTitle: false,
        role: ["SUPER_ADMIN"],
        submenu: [
          {
            path: "/admin/manage-department",
            title: "Manage Department",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/admin/add-department","/admin/edit-department"],
            role: [],
            submenu: [],
          },
          {
            path: "/employee/manage-employee",
            title: "Manage Employee",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/employee/add-employee","/employee/edit-employee","/administrative/employee/excel-import-export"],
            role: [],
            submenu: [],
          },
          {
            path: "/administrative/pay-configuration",
            title: "Pay Configuration",
            icon: "",
            class: "",
            groupTitle: false,
            role: ["SUPER_ADMIN"],
            submenu: [],
          },
          {
            path: "/billing/manage-payroll",
            title: "Manage Employee Pay",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/billing/create-payroll","/billing/edit-payroll"],
            role: [""],
            submenu: [],
          },
          {
            path: "/administrative/employee-monthly-pay",
            title: "Monthly Pay",
            icon: "",
            class: "",
            groupTitle: false,
            role: ["SUPER_ADMIN"],
            submenu: [],
          },
          {
            path: "/employee/manage-employee-pay-hours",
            title: "Manage Employee Pay Hours",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/employee/add-employee-pay-hours","/employee/edit-employee-pay-hours","/administrative/pay-hours/excel-import-export"],
            role: [],
            submenu: [],
          },
          {
            path: "/employee/manage-employee-weekly-wages",
            title: "Manage Employee Weekly Wages",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/employee/add-employee-weekly-wages","/employee/edit-employee-weekly-wages","/administrative/weekly-wages/excel-import-export"],
            role: [],
            submenu: [],
          },
        ],
      },
      {
        path: "",
        title: "Contractor",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [
          {
            path: "/employee/manage-contractor",
            title: "Manage Contractor",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/employee/create-contractor","/employee/edit-contractor"],
            role: [""],
            submenu: [],
          },
          {
            path: "/employee/manage-contract-employee",
            title: "Manage Contract Employees",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/employee/add-contract-employee","/employee/edit-contract-employee", "/administrative/contract-employee/excel-import-export"],
            role: [""],
            submenu: [],
          },
          {
            path: "/employee/manage-contract",
            title: "Manage Contract",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/employee/add-contract","/employee/edit-contract"],
            role: [""],
            submenu: [],
          },
          {
            path: "/employee/manage-contractor-payment",
            title: "Manage Contract Payment",
            icon: "",
            class: "",
            groupTitle: false,
            child:["/employee/edit-contractor-payment"],
            role: [""],
            submenu: [],
          },
        ],
      },
      {
        path: "",
        title: "Activity",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [
          {
            path: "/admin/manage-daily-status",
            title: "Daily Status",
            icon: "",
            class: "",
            groupTitle: false,
            role: [],
            submenu: [],
          },
          {
            path: "/admin/manage-leave-request",
            title: "Leave Approval",
            icon: "",
            class: "",
            groupTitle: false,
            role: [""],
            submenu: [],
          },
          {
            path: "/admin/leave-history",
            title: "Leave History",
            icon: "",
            class: "",
            groupTitle: false,
            role: [""],
            submenu: [],
          },
          {
            path: "/administrative/holiday-tracker",
            title: "Holiday Tracker",
            icon: "",
            class: "",
            groupTitle: false,
            role: [""],
            submenu: [],
          },
          {
            path: "/employee/manage-swipe-entry",
            title: "Swipe Entry",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/employee/add-swipe-entry","/employee/edit-swipe-entry"],
            role: [""],
            submenu: [],
          },
        ],
      },      
    ],
  },

  {
    path: "",
    title: "User",
    icon: "fa fa-user-plus",
    class: "",
    groupTitle: false,
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/user/manage-user",
        title: "Manage User(Login)",
        icon: "",
        class: "",
        groupTitle: false,
        child: ["/user/add-user"],
        role: [],
        submenu: [],
      },
      // {
      //   path: "/user/add-user",
      //   title: "Add User",
      //   icon: "",
      //   class: "",
      //   groupTitle: false,
      //   hide: true,
      //   role: [],
      //   submenu: [],
      // },
      {
        path: "/admin/change-password",
        title: "Change Password",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Customer",
    icon: "fa fa-users",
    class: "",
    groupTitle: false,
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/user/manage-customer",
        title: "Manage Customer",
        icon: "",
        class: "",
        groupTitle: false,
        child: ["/user/add-customer","/user/edit-customer","/administrative/user/excel-import-export"],
        role: [],
        submenu: [],
      },
      {
        path: "/user/manage-customer-wallet",
        title: "Manage Customer Wallet",
        icon: "",
        class: "",
        groupTitle: false,
        child: ["/user/edit-customer-wallet"],
        role: [],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Inventory",
    icon: "fa fa-archive",
    class: "",
    groupTitle: false,
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/inventory/manage-brand",
        title: "Manage Brand",
        icon: "person",
        class: "",
        groupTitle: false,
        child: ["/inventory/add-brand","/inventory/edit-brand"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      {
        path: "/inventory/manage-category",
        title: "Manage Category",
        icon: "ballot",
        class: "",
        groupTitle: false,
        child: ["/inventory/add-category","/inventory/edit-category"],
        role: [],
        submenu: [],
      },
      {
        path: "/inventory/manage-units",
        title: "Manage Units",
        icon: "person",
        class: "",
        groupTitle: false,
        child: ["/inventory/add-units","/inventory/edit-units"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      {
        path: "/inventory/products/manage-items",
        title: "Manage Items",
        icon: "ballot",
        groupTitle: false,
        child: ["/inventory/products/add-items","/inventory/products/edit-items","/inventory/products/add-brand",
        "/inventory/products/add-units","/inventory/products/add-category"],
        class: "",
        role: [],
        submenu: [],
      },
      {
        path: "/production/manage-production-stock",
        title: "Stocks",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Sales Order",
    icon: "fa fa-file-text-o",
    groupTitle: false,
    class: "",
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/order&cart/approve-orders",
        title: "Manage Orders",
        icon: "ballot",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
      {
        path: "/order&cart/pending-orders",
        title: "View Order Details",
        icon: "ballot",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
      {
        path: "/billing/sales-details",
        title: "View Sales Details",
        icon: "ballot",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
    ],
  },

 

  {
    path: "",
    title: "Payment",
    icon: "fa fa-credit-card",
    groupTitle: false,
    class: "",
    role: ["SUPER_ADMIN"],
    submenu: [
      // {
      //   path: "/billing/manage-payment",
      //   title: "Update Payments",
      //   icon: "",
      //   class: "",
      //   groupTitle: false,
      //   role: [],
      //   submenu: [],
      // },
      {
        path: "/billing/payment-status",
        title: "View Payments  ",
        icon: "",
        class: "",
        child:["/administrative/payment/excel-import-export"],
        groupTitle: false,
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      // {
      //   path: "/billing/manage-payment-type",
      //   title: "Manage Payment Type ",
      //   icon: "",
      //   class: "",
      //   groupTitle: false,
      //   role: ["SUPER_ADMIN"],
      //   submenu: [],
      // },
      {
        path: "/billing/credit-payment-tracker",
        title: "Credit Payment Tracker ",
        icon: "",
        class: "",
        groupTitle: false,
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
    ],
  },

 

  {
    path: "",
    title: "Shipment",
    icon: "fa fa-truck",
    groupTitle: false,
    class: "",
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/shipment/update-shipment",
        title: "Update Shipment",
        icon: "person",
        class: "",
        groupTitle: false,
        child:["/shipment/edit-shipment/update-shipment"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      {
        path: "/shipment/shipment-status",
        title: "View Shipment",
        icon: "person",
        class: "",
        groupTitle: false,
        role: ["SUPER_ADMIN"],
        submenu: [],
      },

 

    ],
  },

 

  {
    path: "",
    title: "Production",
    icon: "fa fa-cogs",
    groupTitle: false,
    class: "",
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/production/manage-production",
        title: "Manage Production",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/production/add-production"],
        role: [],
        submenu: [],
      }
    ],
  },

 

  {
    path: "",
    title: "CRM",
    icon: "fa fa-user-secret",
    groupTitle: false,
    class: "",
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/crm/manage-lead-generation",
        title: "Lead Generation",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/crm/add-lead-generation","/crm/edit-lead-generation"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      {
        path: "/crm/manage-lead-followup",
        title: "Lead Followups",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/crm/edit-lead-followup"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
    ],
  },

 

  {
    path: "",
    title: "Machinery",
    icon: "fa fa-cog",
    groupTitle: false,
    class: "",
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/machinery/manage-machinery",
        title: "Manage Machines",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/machinery/add-machinery","/machinery/edit-machinery"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      {
        path: "/machinery/manage-service",
        title: "Manage Machine Services",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/machinery/add-maintenance","/machinery/edit-maintenance"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      // {
      //   path: "/machinery/manage-service-breakdown",
      //   title: "Manage Breakdown",
      //   icon: "",
      //   class: "",
      //   groupTitle: false,
      //   role: ["SUPER_ADMIN"],
      //   submenu: [],
      // },
      {
        path: "/machinery/manage-spares",
        title: "Manage Spare Services",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/machinery/add-spares","/machinery/edit-spares"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      }
    ],
  },
  {
    path: "",
    title: "Vehicle",
    icon: "fa fa-bus",
    class: "",
    groupTitle: false,
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/vehicle/manage-vehicle-type",
        title: "Vehicle Type Management",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/vehicle/add-vehicle-type","/vehicle/edit-vehicle-type"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      {
        path: "/vehicle/manage-service-items",
        title: "Service Items",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/vehicle/add-service-items","/vehicle/edit-service-items"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      {
        path: "/vehicle/manage-vehicle",
        title: "Manage Vehicle",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/vehicle/add-vehicle","/vehicle/edit-vehicle"],
        role: ['SUPER_ADMIN'],
        submenu: [],
      },
      {
        path: "/vehicle/manage-service",
        title: "Service History",
        icon: "person",
        class: "",
        groupTitle: false,
        child:["/vehicle/add-service","/vehicle/edit-service"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      },
      // {
      //   path: "/vehicle/manage-service-breakdown",
      //   title: "Manage Service-Breakdown",
      //   icon: "person",
      //   class: "",
      //   groupTitle: false,
      //   role: ["SUPER_ADMIN"],
      //   submenu: [],
      // },

 

    ],
  },

{
    path: "",
    title: "Expense",
    icon: "fa fa-money",
    groupTitle: false,
    class: "",
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/billing/manage-expense-category",
        title: "Expense Category",
        icon: "ballot",
        class: "",
        child:["/billing/add-expense-category","/billing/edit-expense-category"],
        groupTitle: false,
        role: [],
        submenu: [],
      },
      {
        path: "/billing/manage-expense",
        title: "Manage Expense",
        icon: "ballot",
        class: "",
        groupTitle: false,
        child:["/billing/add-expense","/billing/edit-expense"],
        role: [],
        submenu: [],
      },
    ]
  },
  {
    path: "",
    title: "Administrative",
    icon: "fa fa-user",
    class: "",
    groupTitle: false,
    role: ["SUPER_ADMIN"],
    submenu: [
      {
        path: "/administrative/manage-reject-reason",
        title: "Reject Reason",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/administrative/add-reject-reason","/administrative/edit-reject-reason"],
        role: ["SUPER_ADMIN"],
        submenu: [],
      }
    ],
  },


  // Admin Module ________________________________________________________________________________
  {
    path: "",
    title: "HRA",
    icon: "fa fa-address-card-o",
    class: "",
    groupTitle: false,
    role: ["ADMIN"],
    submenu: [
      {
        path: "",
        title: "Employee",
        icon: "",
        class: "",
        groupTitle: false,
        child:[""],
        role: ["SUPER_ADMIN"],
        submenu: [
          {
            path: "/admin/manage-department",
            title: "Manage Department",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/admin/add-department","/admin/edit-department"],
            role: ["SUPER_ADMIN"],
            submenu: [],
          },
          {
            path: "/employee/manage-employee",
            title: "Manage Employee",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/employee/add-employee","/employee/edit-employee","/administrative/employee/excel-import-export"],
            role: [],
            submenu: [],
          },
          {
            path: "/billing/manage-payroll",
            title: "Manage Employee Pay",
            icon: "",
            class: "",
            groupTitle: false,
            child: ["/billing/create-payroll","/billing/edit-payroll"],
            role: [""],
            submenu: [],
          },
          {
            path: "/administrative/employee-monthly-pay",
            title: "Monthly Pay",
            icon: "",
            class: "",
            groupTitle: false,
            role: ["SUPER_ADMIN"],
            submenu: [],
          },
        ],
      },
      {
        path: "",
        title: "Contractor",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [
          {
            path: "/employee/manage-contractor",
            title: "Manage Contractor",
            icon: "",
            class: "",
            groupTitle: false,
            child:["/employee/create-contractor","/employee/edit-contractor"],
            role: [""],
            submenu: [],
          },
          {
            path: "/employee/manage-contract-employee",
            title: "Manage Contract Employees",
            icon: "",
            class: "",
            groupTitle: false,
            child:["/employee/add-contract-employee","/administrative/contract-employee/excel-import-export"],
            role: [""],
            submenu: [],
          },
          {
            path: "/employee/manage-contract",
            title: "Manage Contract",
            icon: "",
            class: "",
            groupTitle: false,
            child:["/employee/add-contract"],
            role: [""],
            submenu: [],
          },
          {
            path: "/employee/manage-contractor-payment",
            title: "Manage Contract Payment",
            icon: "",
            class: "",
            groupTitle: false,
            child:["/employee/edit-contractor-payment"],
            role: [""],
            submenu: [],
          },
        ],
      },
      {
        path: "",
        title: "Activity",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [
          {
            path: "/admin/manage-daily-status",
            title: "Daily Status",
            icon: "",
            class: "",
            groupTitle: false,
            child:["/admin/add-daily-status","/admin/edit-daily-status"],
            role: [],
            submenu: [],
          },
          {
            path: "/admin/manage-leave-request",
            title: "Leave Approval",
            icon: "",
            class: "",
            groupTitle: false,
            child:["/admin/add-leave-request"],
            role: [""],
            submenu: [],
          },
          {
            path: "/admin/leave-history",
            title: "Leave History",
            icon: "",
            class: "",
            groupTitle: false,
            role: [""],
            submenu: [],
          },
          {
            path: "/employee/manage-swipe-entry",
            title: "Swipe Entry",
            icon: "",
            class: "",
            groupTitle: false,
            child:["/employee/add-swipe-entry","/employee/edit-swipe-entry"],
            role: [""],
            submenu: [],
          },
        ],
      },      
    ],
  },
  {
    path: "",
    title: "User",
    icon: "fa fa-user",
    class: "",
    groupTitle: false,
    role: ["ADMIN"],
    submenu: [
      {
        path: "/user/manage-user",
        title: "Manage User(Login)",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/user/add-user"],
        role: [],
        submenu: [],
      },
      {
        path: "/admin/change-password",
        title: "Change Password",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Customer",
    icon: "fa fa-users",
    class: "",
    groupTitle: false,
    role: ["ADMIN"],
    submenu: [
      {
        path: "/user/manage-customer",
        title: "Manage Customer",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/user/add-customer","/administrative/user/excel-import-export","/user/edit-customer"],
        role: [],
        submenu: [],
      },
      {
        path: "/user/manage-customer-wallet",
        title: "Manage Customer Wallet",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/user/edit-customer-wallet"],
        role: [],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Inventory",
    icon: "fa fa-archive",
    class: "",
    groupTitle: false,
    role: ["ADMIN"],
    submenu: [
      {
        path: "/inventory/manage-brand",
        title: "Manage Brand",
        icon: "person",
        class: "",
        groupTitle: false,
        child: ["/inventory/add-brand","/inventory/edit-brand"],
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "/inventory/manage-category",
        title: "Manage Category",
        icon: "ballot",
        class: "",
        groupTitle: false,
        child: ["/inventory/add-category","/inventory/edit-category"],
        role: [],
        submenu: [],
      },
      {
        path: "/inventory/manage-units",
        title: "Manage Units",
        icon: "person",
        class: "",
        groupTitle: false,
        child: ["/inventory/add-units","/inventory/edit-units"],
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "/inventory/products/manage-items",
        title: "Manage Items",
        icon: "ballot",
        groupTitle: false,
        child: ["/inventory/products/add-items","/inventory/products/edit-items","/inventory/products/add-brand",
        "/inventory/products/add-units","/inventory/products/add-category"],
        class: "",
        role: [],
        submenu: [],
      },
      {
        path: "/production/manage-production-stock",
        title: "Stocks",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Sales Order",
    icon: "fa fa-file-text-o",
    groupTitle: false,
    class: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "order&cart/approve-orders",
        title: "Manage Orders",
        icon: "ballot",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
      {
        path: "order&cart/pending-orders",
        title: "View Order Details",
        icon: "ballot",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
      {
        path: "billing/sales-details",
        title: "View Sales Details",
        icon: "ballot",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
    ],
  },

 

  {
    path: "",
    title: "Payment",
    icon: "fa fa-credit-card",
    groupTitle: false,
    class: "",
    role: ["ADMIN"],
    submenu: [
      // {
      //   path: "/billing/manage-payment",
      //   title: "Update Payments",
      //   icon: "",
      //   class: "",
      //   groupTitle: false,
      //   role: [],
      //   submenu: [],
      // },
      {
        path: "/billing/payment-status",
        title: "View Payments  ",
        icon: "",
        class: "",
        child:["/administrative/payment/excel-import-export"],
        groupTitle: false,
        role: ["ADMIN"],
        submenu: [],
      },
      // {
      //   path: "/billing/manage-payment-type",
      //   title: "Manage Payment Type ",
      //   icon: "",
      //   class: "",
      //   groupTitle: false,
      //   role: ["ADMIN"],
      //   submenu: [],
      // },
      {
        path: "/billing/credit-payment-tracker",
        title: "Credit Payment Tracker ",
        icon: "",
        class: "",
        groupTitle: false,
        role: ["ADMIN"],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Shipment",
    icon: "fa fa-truck",
    groupTitle: false,
    class: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/shipment/update-shipment",
        title: "Update Shipment",
        icon: "person",
        class: "",
        groupTitle: false,
        child:["/shipment/edit-shipment/update-shipment"],
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "/shipment/shipment-status",
        title: "View Shipment",
        icon: "person",
        class: "",
        groupTitle: false,
        role: ["ADMIN"],
        submenu: [],
      },

 

    ],
  },
  {
    path: "",
    title: "Vehicle",
    icon: "fa fa-bus",
    groupTitle: false,
    class: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/vehicle/manage-vehicle-type",
        title: "Vehicle Type Management",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/vehicle/add-vehicle-type","/vehicle/edit-vehicle-type"],
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "/vehicle/manage-service-items",
        title: "Service Items",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/vehicle/add-service-items","/vehicle/edit-service-items"],
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "/vehicle/manage-vehicle",
        title: "Manage Vehicle",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/vehicle/add-vehicle","/vehicle/edit-vehicle"],
        role: ['ADMIN'],
        submenu: [],
      },
      {
        path: "/vehicle/manage-service",
        title: "Maintenance Management",
        icon: "person",
        class: "",
        groupTitle: false,
        child:["/vehicle/add-service","/vehicle/edit-maintenance"],
        role: ["ADMIN"],
        submenu: [],
      },

 


    ],
  },
  {
    path: "",
    title: "Production",
    icon: "fa fa-cogs",
    groupTitle: false,
    class: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/production/manage-production",
        title: "Manage Production",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/production/add-production","/production/edit-production"],
        role: [],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "CRM",
    icon: "fa fa-user-secret",
    groupTitle: false,
    class: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/crm/manage-lead-generation",
        title: "Lead Generation",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/crm/add-lead-generation","/crm/edit-lead-generation"],
        role: [""],
        submenu: [],
      },
      {
        path: "/crm/manage-lead-followup",
        title: "Lead Followups",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/crm/edit-lead-followup"],
        role: [""],
        submenu: [],
      },
    ],
  },


 

  {
    path: "",
    title: "Machinery",
    icon: "fa fa-cog",
    groupTitle: false,
    class: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/machinery/manage-machinery",
        title: "Machine Details",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/machinery/add-machinery","/machinery/edit-machinery"],
        role: ["ADMIN"],
        submenu: [],
      },
      {
        path: "/machinery/manage-service",
        title: "Update Maintenance",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/machinery/add-service","/machinery/edit-maintenance"],
        role: ["ADMIN"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Expense",
    icon: "fa fa-money",
    groupTitle: false,
    class: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/billing/manage-expense-category",
        title: "Expense Category",
        icon: "ballot",
        class: "",
        groupTitle: false,
        child:["/billing/add-expense-category","/billing/edit-expense-category"],
        role: [],
        submenu: [],
      },
      {
        path: "/billing/manage-expense",
        title: "Manage Expense",
        icon: "ballot",
        class: "",
        groupTitle: false,
        child:["/billing/add-expense","/billing/edit-expense"],
        role: [],
        submenu: [],
      },
    ]
  },
  {
    path: "",
    title: "Administrative",
    icon: "fa fa-user",
    class: "",
    groupTitle: false,
    role: ["ADMIN"],
    submenu: [
      {
        path: "/administrative/manage-reject-reason",
        title: "Reject Reason",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/administrative/add-reject-reason","/administrative/edit-reject-reason"],
        role: [""],
        submenu: [],
      },
    ],
  },


  // Employee Modules ____________________________________________________________________________
  {
    path: "",
    title: "User",
    icon: "fa fa-user",
    class: "",
    groupTitle: false,
    role: ["EMPLOYEE"],
    submenu: [
      {
        path: "/admin/change-password",
        title: "Change Password",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "HRA",
    icon: "fa fa-address-card-o",
    class: "",
    groupTitle: false,
    role: ["EMPLOYEE"],
    submenu: [
      {
        path: "/employee/manage-daily-status",
        title: "Daily Status",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/employee/add-daily-status","/employee/edit-daily-status"],
        role: [],
        submenu: [],
      },
      {
        path: "/employee/manage-leave-request",
        title: "Leave Entry",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/employee/add-leave-request"],
        role: ["EMPLOYEE"],
        submenu: [],
      },
      {
        path: "/admin/leave-history",
        title: "Leave History",
        icon: "",
        class: "",
        groupTitle: false,
        role: ["EMPLOYEE"],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Production",
    icon: "fa fa-cogs",
    groupTitle: false,
    class: "",
    role: ["EMPLOYEE"],
    submenu: [
      {
        path: "/production/manage-production",
        title: "Manage Production",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/production/add-production"],
        role: [],
        submenu: [],
      },
    ],
  },

 

  {
    path: "",
    title: "CRM",
    icon: "fa fa-user-secret",
    groupTitle: false,
    class: "",
    role: ["EMPLOYEE"],
    submenu: [
      {
        path: "/crm/manage-lead-generation",
        title: "Lead Generation",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/crm/add-lead-generation","/crm/edit-lead-generation"],
        role: [""],
        submenu: [],
      },
      {
        path: "/crm/manage-lead-followup",
        title: "Lead Followups",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/crm/edit-lead-followup"],
        role: [""],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Machinery",
    icon: "fa fa-cog",
    groupTitle: false,
    class: "",
    role: ["EMPLOYEE"],
    submenu: [
      {
        path: "/machinery/manage-machinery",
        title: "Manage Machines",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/machinery/add-machinery","/machinery/edit-machinery"],
        role: [""],
        submenu: [],
      },
      {
        path: "/machinery/manage-service",
        title: "Manage Machine Services",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/machinery/add-maintenance","/machinery/edit-maintenance"],
        role: [""],
        submenu: [],
      },
      {
        path: "/machinery/manage-spares",
        title: "Manage Spare Services",
        icon: "",
        class: "",
        groupTitle: false,
        child:["/machinery/add-spares","/machinery/edit-spares"],
        role: [""],
        submenu: [],
      }
    ],
  },

 

  // Customer Modules _____________________________________________________________________________________

 

  {
    path: "",
    title: "User",
    icon: "fa fa-user",
    class: "",
    groupTitle: false,
    role: ["CUSTOMER"],
    submenu: [
      {
        path: "/admin/change-password",
        title: "Change Password",
        icon: "",
        class: "",
        groupTitle: false,
        role: [],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "My Order",
    icon: "fa fa-location-arrow",
    groupTitle: false,
    class: "",
    role: ["CUSTOMER"],
    submenu: [
      {
        path: "billing/sales-details",
        title: "View Sales Details",
        icon: "ballot",
        class: "",
        groupTitle: false,
        child:['/billing/sales-details'],
        role: [],
        submenu: [],
      },
    ],
  },

 

  {
    path: "",
    title: "Payment",
    icon: "fa fa-credit-card",
    groupTitle: false,
    class: "",
    role: ["CUSTOMER"],
    submenu: [
      {
        path: "/billing/payment-status",
        title: "View Payments History ",
        icon: "",
        class: "",
        groupTitle: false,
        role: ["CUSTOMER"],
        submenu: [],
      },
      {
        path: "/billing/wallet-history",
        title: "Wallet History",
        icon: "",
        class: "",
        groupTitle: false,
        role: ["CUSTOMER"],
        submenu: [],
      },
    ],
  },

 

  {
    path: "",
    title: "Shipment",
    icon: "fa fa-truck",
    groupTitle: false,
    class: "",
    role: ["CUSTOMER"],
    submenu: [
      {
        path: "/shipment/shipment-status",
        title: "View Shipment",
        icon: "person",
        class: "",
        groupTitle: false,
        role: ["CUSTOMER"],
        submenu: [],
      },
    ],
  },
];