# This workflow efficiently builds and tests your Node.js code across multiple versions.
# For more information on GitHub Actions for Node.js: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Build and Test

on:
  # Trigger on pushes to the main branch and pull requests
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v3  # Fetch code from repository (using recommended v3)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
